[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#0bc122"

# Optimize for Streamlit Cloud
[global]
developmentMode = false




